[theme]
base="dark"
primaryColor="#00FFAA" 
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
